### PR TITLE
Netstandard

### PR DESCRIPTION
**Pull request by flagbug**

### CODE REVIEW

**Comment by ghuntley** [comment]
:tada:

- netstandard v1.0 for punchclock is the correct choice :+1: 
- This uses System.Reactive 3.0 which is :+1: but this will be a breaking change/major will need bumping.


- Need to review meat of PR; let's do that now and get it finished tonight.
- CI can and should be handled as part of seperate PR.

Thank-you @flagbug

**Comment by flagbug** [comment]
@ghuntley The test project has a dependency on the `CreateCollection` method of ReactiveUI, which conflicts with `System.Reactive`

**Comment by ghuntley** [comment]
Yeah, I found similar dependency conflicts with fusillade and will potentially with others as well as Paul used `reactiveui-testing` in quite a few places. So, super important to bring up everything (even without unit tests) w/CI + Publish to MyGet and then re-enable the unit tests on the dependencies. Once things stabilize then do final builds/publish to nuget.org

**Comment by flagbug** [comment]
Ok, so I'll just disbale the unit tests for now

**Comment by flagbug** [comment]
@ghuntley This should be ready

**Comment by ghuntley** [comment]
:shipit:

**Pull request merged**
